- name: 'Create user'
  user:
    name: 'worker'
    state: 'present'

- name: 'Create directory'
  file:
    path: '/var/www/worker'
    state: 'directory'

- name: 'Apply worker.tar'
  unarchive:
    src: 'worker.tar'
    dest: '/var/www/worker'
    extra_opts: '--strip-components=1'

- name: 'Install Java'
  apt:
    name: 'openjdk-11-jdk'
    state: 'present'

- name: 'Install Maven'
  apt:
    name: 'maven'
    state: 'present'

- name: 'Build project'
  shell: 'mvn -f /var/www/worker/pom.xml dependency:resolve && mvn -f /var/www/worker/pom.xml package'

- name: 'Change permissions'
  shell: 'chown -R worker /var/www/worker && find /var/www/worker -type f -exec chmod 0644 {} \; && find /var/www/worker -type d -exec chmod 0755 {} \;'

- name: 'Install service'
  template:
    src: 'templates/worker.j2'
    dest: '/etc/systemd/system/worker.service'
    mode: '0644'
    owner: 'worker'

- name: 'Start Worker'
  service:
    name: 'worker.service'
    state: 'started'
